import { config } from '@/config';
import { get80Server, get443Server } from '@/utils/nginxUtils';

// Reserved nginx conf name for the leader's own dashboard vhost. Prefixed so it can't collide with
// a project conf (`<projectId>.conf`) and sorts after them.
export const DASHBOARD_CONF_NAME = 'zz-nsm-dashboard.conf';

// The dashboard's own public hostname, derived from trusted server config (never request headers).
// Returns null when there's nothing certbot can issue for (plain HTTP, an IP, or a bare host), in
// which case the dashboard stays on http://<leader>:<apiPort> and no vhost is rendered.
export const dashboardDomain = (): string | null => {
    let url: URL;
    try {
        url = new URL(config.publicUrl);
    } catch {
        return null;
    }
    if (url.protocol !== 'https:') return null;
    const host = url.hostname;
    if (host === 'localhost') return null;
    if (/^\d{1,3}(\.\d{1,3}){3}$/.test(host)) return null; // IPv4 literal
    if (host.includes(':')) return null; // IPv6 literal
    if (!host.includes('.')) return null; // bare hostname, not a FQDN
    return host;
};

// nginx vhost that terminates TLS for the dashboard domain and proxies to the local daemon.
//
// The Connection header is driven by the $http_upgrade map (defined below), NOT hardcoded to
// "upgrade". Forcing "upgrade" on every request kept the upstream connection to the daemon open;
// with the daemon's short keep-alive timeout that produced a stale socket nginx would reuse on the
// next page load, failing the first request with a 502 ("upstream prematurely closed connection").
// For ordinary requests the map yields "close", so nginx never reuses a socket the daemon dropped;
// genuine WebSocket upgrades still get "upgrade".
export const buildDashboardConf = (domain: string): string => {
    const location = `
    location / {
        proxy_pass http://127.0.0.1:${config.apiPort};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $nsm_dashboard_connection;
    }`;
    // NSM-specific map variable name: a host nginx.conf commonly already defines a
    // `$connection_upgrade` map, and two maps for the same variable make `nginx -t` fail
    // ("duplicate"), which would block the reload of this (and every) NSM conf.
    return `
# Generated by the Node Server Manager (dashboard ingress)
map $http_upgrade $nsm_dashboard_connection {
    default upgrade;
    ''      close;
}
${get80Server([domain])}
${get443Server([domain], [location])}
`;
};
