import { DeploymentState } from '@mosaiq/nsm-common/types';
import { DesiredDeployment } from '@mosaiq/nsm-common/clusterOps';
import { getGitHttpsUri, getGitSshUri } from '@mosaiq/nsm-common/gitUtils';
import * as fs from 'fs/promises';
import { config, gitSshKeyPath, isGithubAppConfigured } from '@/config';
import { getCloneToken, withCloneCredentials } from '@/utils/githubApp';
import { execSafe, execStream } from '@/host/exec';
import { reportDeploymentLog } from './report';
import { setLocalGeneration } from './state';
import { deployLogger } from '@/utils/log';
import { deploysTotal, deployDuration, errorsTotal } from '@/utils/metrics';

// Applies a fully-rendered DesiredDeployment on this host (clone, write files, docker compose up).
// Direct host exec - no pipe, no worker RPC.
export const applyDeployment = async (dep: DesiredDeployment): Promise<void> => {
    const dlog = deployLogger(dep.projectId, dep.logId);
    const endTimer = deployDuration.startTimer();
    try {
        dlog.info({ generation: dep.generation }, 'reconciling deployment');
        await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, `Reconciling ${dep.projectId} to generation ${dep.generation}...\n`);
        await cloneRepository(dep);
        await injectCompose(dep);
        await injectDotenv(dep);
        await runDeploymentCommand(dep);
        await setLocalGeneration(dep.projectId, dep.generation);
        await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYED, 'Deployment steps completed successfully.\n');
        deploysTotal.inc({ result: 'success' });
        dlog.info('deployment completed');
    } catch (error: any) {
        await reportDeploymentLog(dep.logId, DeploymentState.FAILED, `Failed to deploy project: ${error.message}\n`);
        deploysTotal.inc({ result: 'failure' });
        errorsTotal.inc({ area: 'deploy' });
        dlog.error({ err: error?.message }, 'deployment failed');
    } finally {
        endTimer();
    }
};

const repoPathFor = (projectId: string) => `${config.deploymentPath}/${projectId}`;

const cloneRepository = async (dep: DesiredDeployment): Promise<void> => {
    const repoPath = repoPathFor(dep.projectId);
    const branchFlags = dep.repoBranch ? `-b ${dep.repoBranch} --single-branch` : '';
    try {
        await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, 'Cleaning up old repository...\n');
        await fs.rm(repoPath, { recursive: true, force: true });
    } catch (e: any) {
        throw new Error(`Error cleaning up old repository: ${e.message}`);
    }

    if (!config.production) {
        const httpUri = getGitHttpsUri(dep.repoOwner, dep.repoName);
        const cmd = `git clone ${branchFlags} ${httpUri} ${repoPath}`;
        const { out, code } = await execSafe(cmd, 1000 * 60);
        if (code !== 0) throw new Error(`Git clone exited with code ${code}: ${out}`);
        return;
    }

    // Preferred: GitHub App installation token over HTTPS (no machine user, per-repo, short-lived).
    if (isGithubAppConfigured()) {
        const httpsUri = getGitHttpsUri(dep.repoOwner, dep.repoName);
        await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, `Cloning repository ${httpsUri}...\n`);
        const { token } = await getCloneToken(dep.repoOwner, dep.repoName);
        const { out, code } = await withCloneCredentials(token, (envPrefix) =>
            execSafe(`${envPrefix} git clone --progress ${branchFlags} ${httpsUri} ${repoPath}`, 1000 * 60 * 5)
        );
        if (code !== 0) throw new Error(`Git clone exited with code ${code}: ${out}`);
        await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, `Git clone output:\n${out}\n`);
        return;
    }

    // Fallback: shared SSH deploy key.
    const gitSshUri = getGitSshUri(dep.repoOwner, dep.repoName);
    const sshFlags = `-c core.sshCommand="/usr/bin/ssh -i ${gitSshKeyPath()}"`;
    const cmd = `git clone --progress ${branchFlags} ${sshFlags} ${gitSshUri} ${repoPath}`;
    await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, `Cloning repository ${gitSshUri}...\n`);
    const { out, code } = await execSafe(cmd, 1000 * 60 * 5);
    if (code !== 0) throw new Error(`Git clone exited with code ${code}: ${out}`);
    await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, `Git clone output:\n${out}\n`);
};

const injectDotenv = async (dep: DesiredDeployment): Promise<void> => {
    if (!config.production) return;
    try {
        const contents = `# Generated by NSM - Do not edit directly\n${dep.dotenv}`;
        await fs.writeFile(`${repoPathFor(dep.projectId)}/.env`, contents);
        await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, 'Successfully injected dotenv file\n');
    } catch (e: any) {
        throw new Error(`Error injecting dotenv file: ${e.message}`);
    }
};

const injectCompose = async (dep: DesiredDeployment): Promise<void> => {
    if (!config.production) return;
    const composeFiles = ['docker-compose.yml', 'docker-compose.yaml', 'compose.yaml', 'compose.yml'];
    for (const file of composeFiles) {
        try {
            await fs.rm(`${repoPathFor(dep.projectId)}/${file}`, { force: true, recursive: true });
        } catch {
            /* ignore */
        }
    }
    try {
        const contents = `# Generated by NSM - Do not edit directly\n${dep.compose}`;
        await fs.writeFile(`${repoPathFor(dep.projectId)}/${composeFiles[0]}`, contents);
        await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, 'Successfully injected compose file\n');
    } catch (e: any) {
        throw new Error(`Error injecting compose file: ${e.message}`);
    }
};

const runDeploymentCommand = async (dep: DesiredDeployment): Promise<void> => {
    if (!config.production) return;
    const runCommand = `docker compose -p ${dep.projectId} up --build -d`;
    const deploymentCommand = `(cd ${repoPathFor(dep.projectId)} && ${runCommand})`;
    const { out, code } = await execStream(deploymentCommand, dep.timeout, (data) => {
        void reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, data);
    });
    if (code !== 0) throw new Error(`Deployment command exited with code ${code}: ${out}`);
    await reportDeploymentLog(dep.logId, DeploymentState.DEPLOYING, 'Deployment command completed successfully.\n');
};
