import { CdConfig, CdSetupRequest, Project } from '@mosaiq/nsm-common/types';
import { config, isGithubAppConfigured } from '@/config';
import { getProject, updateProjectNoDirty } from '@/controllers/projectController';
import {
    createBranch,
    createPullRequest,
    deleteBranch,
    deleteRepoFile,
    deleteRepoSecret,
    getBranchSha,
    getRepoFileSha,
    putRepoFile,
    putRepoSecret,
} from '@/utils/githubApp';
import { generateWorkflowYaml, secretNameForProject, workflowPathForProject } from '@/utils/workflowTemplate';
import { areaLog } from '@/utils/log';

const cicdLog = areaLog('cicd');

// Head branch used when committing the workflow via a pull request. Deterministic per project so a
// re-run reuses (and updates) the same branch/PR rather than piling up new ones.
const prBranchForProject = (projectId: string): string => `nsm-cicd-${projectId.replace(/[^A-Za-z0-9._-]/g, '-')}`;

// Provision a managed GitHub Actions workflow for a project: write the deploy key as a repo secret
// and commit a generated workflow file (directly to the deploy branch or via a PR). Persists a
// snapshot of the configuration on the project and enables CI/CD. Leader-only (App private key).
export const setupManagedCd = async (projectId: string, req: CdSetupRequest): Promise<Project | undefined> => {
    if (!isGithubAppConfigured()) throw new Error('The NSM GitHub App is not configured on this node.');
    const project = await getProject(projectId);
    if (!project) return undefined;

    const owner = project.repoOwner;
    const repo = project.repoName;
    const secretName = secretNameForProject(projectId);
    const workflowPath = workflowPathForProject(projectId);

    // 1. Write the deploy key as a repo secret so the workflow can authenticate to the deploy webhook.
    await putRepoSecret(owner, repo, secretName, project.deploymentKey || '');

    const cd: CdConfig = {
        managed: true,
        branch: req.branch,
        triggers: req.triggers,
        branches: req.branches,
        tagPattern: req.tagPattern,
        cron: req.cron,
        viaPr: req.viaPr,
        workflowPath,
        secretName,
        setupAt: Date.now(),
    };

    const yaml = generateWorkflowYaml(project, cd, config.publicUrl);
    const commitMessage = `NSM: add managed deployment workflow for ${projectId}`;

    if (req.viaPr) {
        // Create (or reuse) a dedicated branch off the deploy branch, commit the workflow there, and
        // open a PR back into the deploy branch.
        const headBranch = prBranchForProject(projectId);
        const baseSha = await getBranchSha(owner, repo, req.branch);
        try {
            await createBranch(owner, repo, headBranch, baseSha);
        } catch (e: any) {
            // A 422 means the branch already exists (previous setup attempt) - reuse it.
            cicdLog.info({ action: 'cicd_pr_branch_exists', projectId, headBranch, err: e?.message }, `reusing existing branch ${headBranch}`);
        }
        const existingSha = await getRepoFileSha(owner, repo, workflowPath, headBranch);
        await putRepoFile(owner, repo, workflowPath, yaml, commitMessage, headBranch, existingSha);
        cd.prUrl = await createPullRequest(
            owner,
            repo,
            headBranch,
            req.branch,
            `NSM: managed deployment workflow for ${projectId}`,
            `This pull request adds a managed GitHub Actions workflow (\`${workflowPath}\`) generated by NSM to deploy \`${projectId}\` on ${req.triggers.join(', ')}.`
        );
    } else {
        // Commit the workflow directly to the deploy branch.
        const existingSha = await getRepoFileSha(owner, repo, workflowPath, req.branch);
        cd.commitSha = await putRepoFile(owner, repo, workflowPath, yaml, commitMessage, req.branch, existingSha);
    }

    await updateProjectNoDirty(projectId, { allowCICD: true, cicd: cd });
    cicdLog.info({ action: 'cicd_setup', projectId, viaPr: req.viaPr, triggers: req.triggers }, `managed CI/CD set up for ${projectId}`);
    return await getProject(projectId);
};

// Remove a project's managed workflow: best-effort delete the workflow file, PR branch (if any), and
// the repo secret, then clear the snapshot. Leaves allowCICD for the user to toggle in config.
export const removeManagedCd = async (projectId: string): Promise<Project | undefined> => {
    if (!isGithubAppConfigured()) throw new Error('The NSM GitHub App is not configured on this node.');
    const project = await getProject(projectId);
    if (!project) return undefined;
    const cd = project.cicd;
    if (!cd || !cd.managed) {
        await updateProjectNoDirty(projectId, { cicd: undefined });
        return await getProject(projectId);
    }

    const owner = project.repoOwner;
    const repo = project.repoName;
    const removeMessage = `NSM: remove managed deployment workflow for ${projectId}`;

    // Best-effort cleanup: any single failure (e.g. file already gone) shouldn't block clearing state.
    await deleteRepoFile(owner, repo, cd.workflowPath, removeMessage, cd.branch).catch((e: any) =>
        cicdLog.warn({ action: 'cicd_remove_file_failed', projectId, err: e?.message }, `failed to delete workflow file for ${projectId}`)
    );
    if (cd.viaPr) {
        await deleteBranch(owner, repo, prBranchForProject(projectId)).catch((e: any) =>
            cicdLog.warn({ action: 'cicd_remove_branch_failed', projectId, err: e?.message }, `failed to delete PR branch for ${projectId}`)
        );
    }
    await deleteRepoSecret(owner, repo, cd.secretName).catch((e: any) =>
        cicdLog.warn({ action: 'cicd_remove_secret_failed', projectId, err: e?.message }, `failed to delete secret for ${projectId}`)
    );

    await updateProjectNoDirty(projectId, { cicd: undefined });
    cicdLog.info({ action: 'cicd_removed', projectId }, `managed CI/CD removed for ${projectId}`);
    return await getProject(projectId);
};
