// Type-safe query keys. Every key's root segment is a `QueryKey` enum member (never a bare string),
// so a typo can't silently create a new cache bucket. Each factory returns a readonly tuple that
// React Query uses structurally for caching and invalidation.

export enum QueryKey {
    Me = 'me',
    Projects = 'projects',
    ProjectStatuses = 'project-statuses',
    WorkerNodes = 'worker-nodes',
    ControlPlaneStatus = 'control-plane-status',
    Domains = 'domains',
    DomainRequests = 'domain-requests',
    DomainBilling = 'domain-billing',
    PublicIp = 'public-ip',
    DnsRecords = 'dns-records',
    DnsAnalytics = 'dns-analytics',
    PortReservations = 'port-reservations',
    Teams = 'teams',
    Team = 'team',
    Admins = 'admins',
    NodeMetrics = 'node-metrics',
    NodeStorage = 'node-storage',
    NodeStorageSeries = 'node-storage-series',
    NodeConfig = 'node-config',
    NodePortReservations = 'node-port-reservations',
    JoinInfo = 'join-info',
    ProjectApiKeys = 'project-api-keys',
    ProjectIncidents = 'project-incidents',
    ProjectWebhooks = 'project-webhooks',
    ProjectDomains = 'project-domains',
    ProjectPortReservations = 'project-port-reservations',
    ProjectResourceUsage = 'project-resource-usage',
    ProjectHealth = 'project-health',
    ProjectDeployAverage = 'project-deploy-average',
    ObservabilityMetrics = 'observability-metrics',
    ProjectInstance = 'project-instance',
    GithubRepos = 'github-repos',
    GithubBranches = 'github-branches',
    PushPreference = 'push-preference',
    Logs = 'logs',
    LogFacets = 'log-facets',
}

export const queryKeys = {
    me: () => [QueryKey.Me] as const,
    projects: () => [QueryKey.Projects] as const,
    projectStatuses: () => [QueryKey.ProjectStatuses] as const,
    workerNodes: () => [QueryKey.WorkerNodes] as const,
    controlPlaneStatus: () => [QueryKey.ControlPlaneStatus] as const,
    domains: () => [QueryKey.Domains] as const,
    domainRequests: () => [QueryKey.DomainRequests] as const,
    domainBilling: () => [QueryKey.DomainBilling] as const,
    publicIp: () => [QueryKey.PublicIp] as const,
    dnsRecords: (zoneId: string) => [QueryKey.DnsRecords, zoneId] as const,
    dnsAnalytics: (zoneId: string) => [QueryKey.DnsAnalytics, zoneId] as const,
    portReservations: () => [QueryKey.PortReservations] as const,
    teams: () => [QueryKey.Teams] as const,
    team: (ownerId: string) => [QueryKey.Team, ownerId] as const,
    admins: () => [QueryKey.Admins] as const,
    nodeMetrics: (nodeId: string, metric: string, range: string) => [QueryKey.NodeMetrics, nodeId, metric, range] as const,
    nodeStorage: (nodeId: string) => [QueryKey.NodeStorage, nodeId] as const,
    nodeStorageSeries: (nodeId: string, range: string) => [QueryKey.NodeStorageSeries, nodeId, range] as const,
    nodeConfig: (nodeId: string) => [QueryKey.NodeConfig, nodeId] as const,
    nodePortReservations: (nodeId: string) => [QueryKey.NodePortReservations, nodeId] as const,
    joinInfo: () => [QueryKey.JoinInfo] as const,
    projectApiKeys: (projectId: string) => [QueryKey.ProjectApiKeys, projectId] as const,
    projectIncidents: (projectId: string) => [QueryKey.ProjectIncidents, projectId] as const,
    projectWebhooks: (projectId: string) => [QueryKey.ProjectWebhooks, projectId] as const,
    projectDomains: (projectId: string) => [QueryKey.ProjectDomains, projectId] as const,
    projectPortReservations: (projectId: string) => [QueryKey.ProjectPortReservations, projectId] as const,
    projectResourceUsage: (projectId: string) => [QueryKey.ProjectResourceUsage, projectId] as const,
    projectHealth: (projectId: string, window: string) => [QueryKey.ProjectHealth, projectId, window] as const,
    projectDeployAverage: (projectId: string) => [QueryKey.ProjectDeployAverage, projectId] as const,
    observabilityMetrics: (selectorKey: string, metric: string, range: string) => [QueryKey.ObservabilityMetrics, selectorKey, metric, range] as const,
    projectInstance: (instanceId: string) => [QueryKey.ProjectInstance, instanceId] as const,
    githubRepos: (owner: string) => [QueryKey.GithubRepos, owner] as const,
    githubBranches: (owner: string, repo: string) => [QueryKey.GithubBranches, owner, repo] as const,
    pushPreference: (projectId: string) => [QueryKey.PushPreference, projectId] as const,
    logs: (inputsKey: string) => [QueryKey.Logs, inputsKey] as const,
    logFacets: (inputsKey: string) => [QueryKey.LogFacets, inputsKey] as const,
};
